"""Assemble the mixed real+synthetic training config for the detector.

Usage:
    python scripts/build_real_mix.py

Writes ``data/datasets/real_mix/data.yaml`` pointing at three sources that all
share the frozen 12-class taxonomy:

* ``synth_xl``  - 100 physics-simulated side-scan scenes (true boxes)
* ``klsg_yolo`` - real side-scan chips, weak measured boxes (academic use)
* ``uatd_yolo`` - real forward-looking sonar, real annotated boxes (CC BY 4.0)

This is a *config generator*, not a copier: Ultralytics accepts lists of image
directories, so the images stay where their builders put them and nothing is
duplicated on disk. The script exists so the mix cannot be assembled by hand
differently on different days - it verifies every source is present, is in the
same class order, and prints the resulting composition so the imbalance is a
recorded number rather than a surprise.

The composition is deliberately imbalanced toward UATD (it is the only source
with real boxes at scale) and that is a measured risk: the post-training gates
re-run the synthetic evaluation and the demo survey, and a regression there
fails the run rather than shipping quietly.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from tridentnet.classes import CLASS_NAMES

REPO_ROOT = Path(__file__).resolve().parents[1]
DATASETS = REPO_ROOT / "data" / "datasets"
OUT_DIR = DATASETS / "real_mix"

#: Sources in the mix. Order is presentation only; Ultralytics concatenates.
SOURCES = ("synth_xl", "klsg_yolo", "uatd_yolo")


def _check_source(name: str) -> dict[str, int]:
    """Verify one source exists, matches the taxonomy, and count its images."""
    root = DATASETS / name
    data_yaml = root / "data.yaml"
    if not data_yaml.is_file():
        raise SystemExit(f"{name}: missing {data_yaml} - build that dataset first")
    doc = yaml.safe_load(data_yaml.read_text(encoding="utf-8"))
    names = doc.get("names") or {}
    expected = dict(enumerate(CLASS_NAMES))
    if {int(k): v for k, v in names.items()} != expected:
        raise SystemExit(
            f"{name}: class map differs from the frozen taxonomy - training on "
            "mismatched indices would silently cross-label every box"
        )
    counts = {}
    for split in ("train", "val"):
        img_dir = root / "images" / split
        counts[split] = sum(1 for p in img_dir.iterdir() if p.is_file()) if img_dir.is_dir() else 0
        if counts[split] == 0:
            raise SystemExit(f"{name}: {img_dir} is empty")
    return counts


def build() -> Path:
    composition: dict[str, dict[str, int]] = {}
    for name in SOURCES:
        composition[name] = _check_source(name)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / "data.yaml"
    out.write_text(
        "# Mixed real + synthetic detector training set. GENERATED by\n"
        "# scripts/build_real_mix.py - edit that script, not this file.\n"
        "#\n"
        "# Composition (images):\n"
        + "".join(
            f"#   {name:10s} train {c['train']:5d}  val {c['val']:4d}\n"
            for name, c in composition.items()
        )
        + "#\n"
        "# Licences: UATD CC BY 4.0; KLSG academic use only - this mix must not\n"
        "# train a commercial build. Synthetic carries no restriction.\n"
        "#\n"
        "# AUGMENTATION: fliplr must stay 0.0 (see scripts/train_detector.py).\n"
        + yaml.safe_dump(
            {
                "path": str(DATASETS).replace("\\", "/"),
                "train": [f"{name}/images/train" for name in SOURCES],
                "val": [f"{name}/images/val" for name in SOURCES],
                "names": dict(enumerate(CLASS_NAMES)),
            },
            sort_keys=False,
        ),
        encoding="utf-8",
    )
    total_t = sum(c["train"] for c in composition.values())
    total_v = sum(c["val"] for c in composition.values())
    print(f"wrote {out}")
    for name, c in composition.items():
        share = 100.0 * c["train"] / max(total_t, 1)
        print(f"  {name:10s} train {c['train']:5d} ({share:4.1f}%)  val {c['val']:4d}")
    print(f"  {'TOTAL':10s} train {total_t:5d}          val {total_v:4d}")
    return out


if __name__ == "__main__":
    build()
